### ISSUE TITLE
back image instead of default image on gallery when some fields are missing

### ISSUE THREAD

**Issue by roumano** [ltb-project/white-pages#100]
Only on the gallery ( it's working as expected on the Entry display) if a user :
- don't have a picture on the ldap database (on jpegphoto field) 
- AND if it's also missing field `employeeNumber` and `roomNumber`,  
 
The gallery show a black image instead of default not-found image for that person

We configured the gallery as this in `conf/config.inc.php` :  
```
# Gallery
$use_gallery = true;
$gallery_title = "fullname";
$gallery_sortby = "lastname";
$gallery_bootstrap_column_class = "col-xs-6 col-sm-4 col-md-3";
$gallery_truncate_title_after = 25;
```

It's not a big issue but it's a strange behavior and confuse users.
PS : we use the White Pages v0.3 (stable) version

**Comment by coudot** [comment]
I don't see the relation between the photo and other attributes. Don't you have any error in logs?

**Comment by roumano** [comment]
I also don't see any relation about this, but i found this strange relation after comparing few account and a try to add/remove these fields on the ldap ...

Yes i have some error too, i have 3 back images in gallery , so i get 3 times these errors :

```
[Fri Dec 04 14:56:15.152243 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Notice:  Undefined variable: photo_local_ldap_attribute in /usr/share/white-pages/htdocs/photo.php on line 46, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.152460 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagecreatefromjpeg(images/240px-PICA.jpg): failed to open stream: No such file or directory in /usr/share/white-pages/htdocs/photo.php on line 62, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.152766 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagesx() expects parameter 1 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 67, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153101 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagesy() expects parameter 1 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 67, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153156 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  Division by zero in /usr/share/white-pages/htdocs/photo.php on line 67, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153439 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagesx() expects parameter 1 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 72, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153491 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagesy() expects parameter 1 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 72, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153538 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagecopyresampled() expects parameter 2 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 72, referer: https://phonebook.embl.fr/index.php?page=gallery
[Fri Dec 04 14:56:15.153795 2020] [:error] [pid 18803] [client 172.26.115.2:33248] PHP Warning:  imagedestroy() expects parameter 1 to be resource, boolean given in /usr/share/white-pages/htdocs/photo.php on line 73, referer: https://phonebook.embl.fr/index.php?page=gallery
```

**Comment by coudot** [comment]
Did you configure $photo_local_directory?

**Comment by roumano** [comment]
No, only use from ldap

**Comment by coudot** [comment]
Are you sure the jpegPhoto attribute is not present? If it is present with an empty value, this would create this bug

**Comment by roumano** [comment]
Yes sure  at 100% the field jpegPhoto not exist on them, i just verify right now

**Comment by coudot** [comment]
The issue is here:
```imagecreatefromjpeg(images/240px-PICA.jpg) : failed to open stream: No such file or directory

**Comment by roumano** [comment]
I just try to copy the default image (attached here) to images/240px-PICA.jpg and i don't have anymore back image
so maybe Yes (it's the defaut configuration) it's related to this issue.

But i  still don't understand why i have a back image on account where field `employeeNumber` and `roomNumber` are not existing and other use the default image out of the box

![photo php_ok](https://user-images.githubusercontent.com/6402894/101180312-b5793a00-364b-11eb-9ecc-398f899a39c4.jpeg)

**Comment by coudot** [comment]
There should be a PHP limitation on open files, it will fail to open config.local.inc.php and failback to config.inc.php
