### ISSUE TITLE
[WP 0.3] Difficulties to display jpegPhoto

### ISSUE THREAD

**Issue by micter59** [ltb-project/white-pages#102]
Hello, 

First, I want to thank you for your good job in the ltb-project.
I'm using many of your application in a project.
I'll replace an old Apache Directory Server with OpenLDAP and WP, SSP and Service-Desk.
I'm setting this through docker containers. I mention this, because this can be involved somewhere...

Everything is ok with white-pages. I can display the page, information about users, the gallery page, etc.
But I can't see images.
I've put data in my openldap, uploaded a jpg photo with Apache Directory Studio.
I this application, I can see the image.

But nothing in white-pages :-( Even the default picture won't display.
The "alt" attribute of the "img" is displayed.
Looking in the log, I don't understand everything, but here what I've found :

`"GET /photo.php?dn=cn%3Dabl%2Cou%3Dlabo%2Cou%3Dusers%2Cdc%3Dlps59 HTTP/1.1" 500 181 "http://localhost:8001/index.php?page=search" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0" 11 1896 0 23 localhost:80`

So the src of the jpeg is not found. It's like the page "photo.php" can't access to the date.
Here's an other part of the log : 
[Thu Mar 11 10:23:11.298515 2021] [php7:error] [pid 23] [client 172.20.0.1:59554] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefromstring() in /usr/share/white-pages/htdocs/photo.php:57\nStack trace:\n#0 {main}\n  thrown in /usr/share/white-pages/htdocs/photo.php on line 57, referer: http://localhost:8001/index.php?page=search

And for all attributes which should be return by the LDAP : 
```
[Thu Mar 11 10:23:11.217709 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Undefined index: employeenumber in /usr/share/white-pages/templates_c/1fc82345f35f5b2f93954f9c0102f878b2e3228f_2.file.display.tpl.php on line 59, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.217717 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Trying to access array offset on value of type null in /usr/share/white-pages/templates_c/1fc82345f35f5b2f93954f9c0102f878b2e3228f_2.file.display.tpl.php on line 59, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.217802 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Undefined index: gosamailquota in /usr/share/white-pages/templates_c/1fc82345f35f5b2f93954f9c0102f878b2e3228f_2.file.display.tpl.php on line 59, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.217811 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Trying to access array offset on value of type null in /usr/share/white-pages/templates_c/1fc82345f35f5b2f93954f9c0102f878b2e3228f_2.file.display.tpl.php on line 59, referer: http://localhost:8001/index.php?page=gallery
```

And before that, a long list of : 
```
172.20.0.1 - - [11/Mar/2021:10:19:38 +0100] "GET /photo.php?dn=cn%3Dabl%2Cou%3Dlabo%2Cou%3Dusers%2Cdc%3Dlps59 HTTP/1.1" 500 181 "http://localhost:8001/index.php?page=search" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0" 11 1857 0 21 localhost:80
vhost_combined
[Thu Mar 11 10:23:11.214485 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Undefined variable: logout_link in /usr/share/white-pages/htdocs/index.php on line 77, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.216637 2021] [php7:notice] [pid 21] [client 172.20.0.1:59536] PHP Notice:  Undefined index: vcard in /usr/share/white-pages/htdocs/display.php on line 61, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.216948 2021] [php7:warn] [pid 21] [client 172.20.0.1:59536] PHP Warning:  Illegal string offset 'count' in /usr/share/white-pages/htdocs/display.php on line 83, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.216962 2021] [php7:warn] [pid 21] [client 172.20.0.1:59536] PHP Warning:  Illegal string offset 'count' in /usr/share/white-pages/htdocs/display.php on line 83, referer: http://localhost:8001/index.php?page=gallery
[Thu Mar 11 10:23:11.216967 2021] [php7:warn] [pid 21] [client 172.20.0.1:59536] PHP Warning:  Illegal string offset 'count' in /usr/share/white-pages/htdocs/display.php on line 83, referer: http://localhost:8001/index.php?page=gallery
```
It seems like some functions were not accessible from the photo.php page, or something like that.
Don't hesitate to ask for more informations.

Thanks for your help !

Michaël

**Comment by coudot** [comment]
Be sure to install required dependencies, like `php-gd`

**Comment by micter59** [comment]
Génial !
That was just this.
Thanks a lot for your very quick answer.

Michaël
