### ISSUE TITLE
Bad value displayed when attribute type is a list

### ISSUE THREAD

**Issue by gauburti** [ltb-project/white-pages#108]
Hi,

We use entities for dropdown-list

```
$attributes_list = array(
    'organizationalunit' => array('base'=>'ou=structures,dc=test,dc=fr','filter'=>'(objectClass=organizationalUnit)','key'=>'supanncodeentite','value'=>'ou'),
    'postaladdress' => array('base'=>'ou=structures,dc=test,dc=fr','filter'=>'(objectClass=organizationalUnit)','key'=>'supanncodeentite','value'=>'ou'),
    );
```

There is a group filter in config

`$ldap_group_filter = "(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames))"`;

Could an entity filter be implemented ? 

such as

`$ldap_entity_filter = "(&(objectClass=supannEntite)(supannCodeEntiteParent=XXX))";`

Is there any workaround ?

Regards

**Comment by gauburti** [comment]
Hi,

it looks like not.

With 
`
`'key'=>'supanncodeentite','value'=>'description'`
`
I get description on search mode (select)
and supanncodeEntite  on display mode (user)

regards

**Comment by coudot** [comment]
Indeed, the value of the attribute is displayed. If attribute is a list, we should consider that the attribute value is list key, and display the associated value in the list.
