### ISSUE TITLE
WP not connecting to my ldap server

### ISSUE THREAD

**Issue by YohanRodriguezMDM** [ltb-project/white-pages#114]
Hi, 
I followed documentation and configured my ldap server/credentials in `config.inc.local.php` file but when I access the webapp, my web server does not access to my ldap server.
Telnet is OK
Any ideas ?

Thanks

**Comment by coudot** [comment]
Enable debug and check the logs

**Comment by YohanRodriguezMDM** [comment]
Debug enabled, here is what I have in wp_error.log : 

`[Tue Mar 22 09:09:48.459909 2022] [php7:warn] [pid 17885] [client 10.10.0.11:53645] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/white-pages/lib/ldap.inc.php on line 18, referer: http://my-server-fqdn/index.php?page=directory
[Tue Mar 22 09:09:48.459965 2022] [php7:notice] [pid 17885] [client 10.10.0.11:53645] LDAP - Bind error -1  (Can't contact LDAP server), referer: http://my-server-fqdn/index.php?page=directory
`

**Comment by coudot** [comment]
Check the network between your web server and your LDAP directory.

If you're using SELinux, configure it correctly.

**Comment by YohanRodriguezMDM** [comment]
I can do a `ldapsearch`from my WP server to the ldap server successfully. 
I just don't see any request going out from the server (tcpdump) when I try to use WP.

**Comment by YohanRodriguezMDM** [comment]
Finally found the solution.
My `config.inc.local.php` was starting with `<?` instead of `<?php`
