### ISSUE TITLE
WP incompatible with PHP 8+ (ldap_sort)

### ISSUE THREAD

**Issue by slapcat** [ltb-project/white-pages#115]
I tried to install a fresh instance of WP on Debian 11 via the `deb` package. While the front page will load, the search, directory, and gallery all produce a completely blank white page. The only error that comes up is the below. After some research, I found that the `ldap_sort` function was deprecated in PHP7 and **completely removed** in PHP8.

```
[Mon Jun 13 17:46:34.478007 2022] [proxy_fcgi:error] [pid 4891] [client 172.100.40.95:51276] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
ldap_sort() in /usr/share/white-pages/htdocs/directory.php:63\nStack trace:\n#0 /usr/share/white-pages/htdocs/index.php(107): require_once()\n#1 {main}\n  thrown in /usr/share/white-pages
/htdocs/directory.php on line 63', referer: http://directory.example.com/index.php
```

Is there a timeline for when this deprecated function will be removed and WP made compatible with PHP8?

**Comment by coudot** [comment]
Indeed this is annoying, we have to remove this function from our code base.

**Comment by coudot** [comment]
@slapcat For now, you could try to set in your configuration:
```php
$search_result_sortby = false;
$gallery_sortby = false;
$directory_sortby = false;
```

It should bypass the calls to `ldap_sort`.

**Comment by slapcat** [comment]
Thanks for the quick response! Another workaround I devised was to specify PHP7 within that specific Apache virtual host:

```
    <FilesMatch \.php$>
      SetHandler "proxy:unix:/run/php/php7.4-fpm.sock|fcgi://localhost"
    </FilesMatch>
```

In either case it works solidly after that :smiley:

**Comment by sblaisot** [comment]
setting sortby config variables to false didn't do the trick for me with php 8.1.

I had better luck with

```
unset($search_result_sortby);
unset($gallery_sortby);
unset($directory_sortby);
```

This is because the code uses `isset()` which eval to `true` on a variable set to `false`:

```
<?php
$a = false;
var_dump(isset($a));
?>
bool(true)
```

**Comment by artlog** [comment]
i hit this problem too when working on issue #119 
i will take look on it soon.
