### ISSUE TITLE
Use LTB LDAP common lib

### ISSUE THREAD

**Issue by coudot** [ltb-project/white-pages#119]
The goal is to write a new composer lib, which would be common to SSP/WP/SD

Step 1 : create the lib (for example LTB-LDAP), starting by the wp_ldap_connect function (rename it to ltb_ldap_connect)
Step 2 : publish it?
Step 3 : Use it in White Pages by removing the ldap.inc.php and using the composer lib

**Comment by coudot** [comment]
Use https://github.com/ltb-project/ltb-ldap

**Comment by bilbo-the-hobbit** [comment]
hello @coudot

We created a new ldap library at FusionDirectory to be used in all our console tools https://gitlab.fusiondirectory.org/fusiondirectory/fusiondirectory-ldap

maybe it would be interesting to collaborate on this one, so it can be used in all programs

Cheers

**Comment by coudot** [comment]
Need to apply the changes to map feature
