### ISSUE TITLE
Gallery and photo filename in whites page

### ISSUE THREAD

**Issue by vlepetit** [ltb-project/white-pages#13]
Hi,

I try to display photo to my users in her white page and gallery.

I put photo in 
/usr/share/white-pages/htdocs/images

and now i try to give the good name to the file to work but it's don't work...

What is the good file name ? 
firstname-lastname.jpg ?

this is the same firstname and last name found in ldap ? 
which attribute exactly ?

regards,
vlepetit

**Comment by vlepetit** [comment]
Ok i understand.

The photo need to be in ldap...

Could you integrate an optional solution to display photo based on file storage ?

Regards,
vlepetit

**Comment by coudot** [comment]
Yes this can be a new feature

**Comment by vlepetit** [comment]
Great !!

I hope than i can test it !!

**Comment by vlepetit** [comment]
I had make a little add to your photo.php to load file if photo isn't in ldap.

Can i propose the code to you ?

**Comment by coudot** [comment]
The best is to propose a pull request

**Comment by vlepetit** [comment]
I tried to uplaod my file but for now i can't.

I need to learn how git works....

At this time i had create a repository on my profil.

I continu to search...

regards,

**Comment by coudot** [comment]
The best is to click on "fork" at the top of this page, then modify the code in the forked repo, then propose a pull request.

**Comment by vlepetit** [comment]
Ok it's done but i'm not sur is in one the right place...
