### ISSUE TITLE
New map feature incorrectly deployed : missing map.js

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/white-pages#133]
(at least) map.js is missing in (at least) RPM files.

This file should be present in htdoc/js directory, which is a new directory, not yet included in RPM packaging

**Comment by davidcoutadeur** [comment]
- debian files are correctly deployed
- seems no other file is missing

See https://github.com/ltb-project/white-pages/pull/134 (untested, but should work)

Note I don't have permissions to push a new branch on this repository.

**Comment by coudot** [comment]
Thanks for the fix!
