### ISSUE TITLE
Print results as rows or boxes

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#16]
Hello,

It could be nice to have an option in config file to change display of results (rows or boxes). 

Advantages of rows results in comparison of boxes results : 
- you can print directly HTML page for end users;
- you can sort results by columns;
- you can display more information on results page;

Proposal : add a config option `display_results` in Full Display's section of `config.inc.php` with two values : 
- rows
- boxes

**Comment by coudot** [comment]
Displaying a table should not be too difficult, adding sort by column is more complex.

**Comment by coudot** [comment]
First implementation done. I still need to add a link in each row to display entry.

**Comment by coudot** [comment]
See if we can use the same display than the directory page done in #25
