### ISSUE TITLE
Quick search return with pattern like "foo*"

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#17]
Hello,

At 2d51174, when doing a quick search with pattern like "foo*", White Pages just returns "entries found" message **without** results. Associated search filter `(|(uid=*foo**)(cn=*foo**)(mail=*foo**))`

White Pages should return same entries found with "foo" pattern.

**Comment by coudot** [comment]
Indeed this is a bug. If no entries found, the correct error message should be displayed.

**Comment by coudot** [comment]
Done. The test on error number was wrong.

**Comment by nqb** [comment]
At cfae137, message prints to the user when using pattern like "foo*" : "LDAP communication error".

To my mind, it's a "Bad search filter error". Could you override PHP LDAP error message to print a more friendly message like :  "Forbidden pattern in search"

**Comment by nqb** [comment]
Currently, error message "LDAP communication error" leads users to believe a technical error on software. This implies bad reputation for White Pages. Search error message seems more accurate (i.e. Incorrect search : `*` not allowed).

**Comment by coudot** [comment]
I'm not sure that overriding PHP LDAP messages is a good idea, but it is maybe the only option. We should also see how to prevent user from doing an invalid search

**Comment by nqb** [comment]
#21

**Comment by coudot** [comment]
Fixed by #21
