### ISSUE TITLE
Replace exact matching by substring matching in advanced search

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#18]
Hello,

As mentioned in [Advanced search's doc](https://ltb-project.org/documentation/white-pages/latest/config_advanced_search), search is done :

>  with an exact or ordering matching

unlike quick search which use : 

>  a substring match (attribute=*query*)

It will be nice to replace exact matching by substring matching in advanced search to have same behaviors.

Currently, when you do a search with "foo" in quick and advanced search (First name field), results are : 
* X entries found (quick search)
* No entries found (advanced search)

**Comment by coudot** [comment]
Quick search filter is done to be the more easy to use, you type some characters and you obtain a lot of results. Advanced search is done to restrict results. I'm not sure to change this behavior.

**Comment by nqb** [comment]
Further informations : 
* If you search `foo*` in advanced search, you get results ! Strange behavior, isn't it ?
* Several White Pages's users agree with my opinion  : misunderstanding between quick and advanced search behavior

If you don't want to change behavior between quick and advanced search, please consider these options : 

- add warning on exact matching in Advanced Search's page;
- give substring matching configurable for Advanced Search

**Comment by coudot** [comment]
We could indeed add a configuration settings for this. I also plan to add some tooltips to help users with the software.

**Comment by nqb** [comment]
Ok @coudot.

What about results with `foo*` pattern in First Name field for example ?

**Comment by coudot** [comment]
'*' is supposed to work in advanced search, not in quick search. A configuration settings will be added to change this behavior.

**Comment by coudot** [comment]
Reopen to see if we need to add an option for the quicksearch

**Comment by nqb** [comment]
My feedback on last commits : 

### with $quick_search_use_substring_match = false; (default)

* Searching `foo` returns : no results
* Searching `foo*` returns : results

### with $quick_search_use_substring_match = true;

* Searching `foo` returns : results
* Searching `foo*` returns : no results

### before commits 
* Searching `foo` returns : results
* Searching `foo*` returns : LDAP error

I think there is an issue or a misunderstanding.

**Comment by coudot** [comment]
Seems ok to me. If you use substring matching, foo* will be converted into foo\*, so there will be no results.

**Comment by nqb** [comment]
OK. I didn't see that you change default behavior for quick search from substring matching to exact matching. It's ok for me.
