### ISSUE TITLE
Display all entries with use_gallery = false

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#19]
Hello,

At 2d51174, to display all entries, there is two methods : 

1. Click on Advanced search -> `First name = * `-> Click on Search
or
2. Click on Gallery

When you set `use_gallery = false` in config, you lose second method. It will be nice to keep this second method with `use_gallery = false` but to display all entries **without** photos. 

My proposal : 
- Replace "Gallery" menu by "Directory" menu
- `use_gallery = false` option disable photos in White Pages but keep "Directory" menu usable to display all entries

**Comment by coudot** [comment]
I would prefer to add a new feature which would be Directory which would display all entries in alphabetical order, like a phone directory.
