### ISSUE TITLE
Plans for a full ldap management?

### ISSUE THREAD

**Issue by Chefkeks** [ltb-project/white-pages#2]
Hi there!

I know you're at v0.1 and there hopefully will be more versions in the future with new and improved features, but there is one question I'd like to know. Are you planning to keep it "read-only" or are there any plans to add features to make white-pages an alternative to manage ldap (e.g. like phpldapadmin)?

Regards,
Michael

**Comment by coudot** [comment]
Hi @Chefkeks, 

there are no specific plans, but for the moment I will keep the application readonly. There are other tools like FusionDirectory for LDAP administration.

**Comment by Chefkeks** [comment]
Thanks for the quick response!
