### ISSUE TITLE
Display specific Attribute of user's Organizational Unit with own structural classe

### ISSUE THREAD

**Issue by vlepetit** [ltb-project/white-pages#20]
Hi,

In my ldap scheme (Supann) my users are affected to Organizational Unit entity with own structural classe.

So the spécific attribute name in attribute_map for organizationalunit is "supannentiteaffectation" .For one user is just a entity code that are the RDN of Entity.

I like to display the "description" or "ou" attribute of this Entity ( like team name or bulding name ).

Can i integrate a sub ldap request to display the spécific attribute of entity in place of attribute define in attribute_map ?

Regards,
vlepetit

**Comment by coudot** [comment]
Hello @vlepetit ,

take a look at the type 'dn_link' in templates/value_displayer.tpl:
```smarty
{if $type eq 'dn_link'}
    <a href="index.php?page=display&dn={$value|escape:'url'}&search={$search}">
    {{get_attribute dn="{$value}" attribute="cn" ldap_url="{$ldap_params.ldap_url}" ldap_starttls="{$ldap_params.ldap_starttls}" ldap_binddn="{$ldap_params.ldap_binddn}" ldap_bindpw="{$ldap_params.ldap_bindpw}" ldap_user_filter="{$ldap_params.ldap_user_filter}"}|truncate:{$truncate_value_after}}
    </a>
{/if}
```

You can create a new type and adapt the call to get_attribute to display what you want.

**Comment by vlepetit** [comment]
ok,
i try to create a new type "entity" and give this new type in attribute_map->
I have to search attribute "ou" or "description" from entite object who are in another basedn than users 
users -> "ou=people",dc=mydomain,dc=fr"
entity -> "ou=structures",dc=mydomain,dc=fr"

so i try to give the dn of object but this don't work a this time.
 
{if $type eq 'entity'}
    {{get_attribute dn="supanncodeentite={$value},ou=structures,dc=xxx,dc=xx" attribute="ou" ldap_url="{$ldap_params.ldap_url}" ldap_starttls="{$ldap_params.ldap_starttls}" ldap_binddn="{$ldap_params.ldap_binddn}" ldap_bindpw="{$ldap_params.ldap_bindpw}"}|truncate:{$truncate_value_after}}
{/if}

I think dn parameter use base dn setup in config file and don't like the full dn that i give in code....

I continu to search but if you have an idea....

regards,

**Comment by coudot** [comment]
No the get_attribute method directly reads the provided DN, see https://github.com/ltb-project/white-pages/blob/ba480e9d80a2cb711c0bd848babd6e9b7a74e270/lib/smarty.inc.php#L7

I think the issue is that the DN you give is wrong. You may create a new "get_attribute" method that will search for your entity entry.

**Comment by vlepetit** [comment]
Ok,

I had found. It was a filter problem in new type of displayer. now i can display the good attribute.

Thanks.
