### ISSUE TITLE
[Security] LDAP Injection in quick search

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#21]
Hello,

Currently, it is possible to make an LDAP injection when using quick search because `$search_query` is use directly in `$ldap_filter`.

Steps to reproduce : 
- Go https://ltb-project.org/star-pages/
- In quick search, enter `c3po)(uid=*sky`
=> WP returns three results : c3po, lskywalker, askywalker

With this kind of `$search_query`, you can request an LDAP attribute which not mentioned in `$quick_search_attributes`.

**Comment by coudot** [comment]
We indeed need to use ldap_escape: http://php.net/manual/en/function.ldap-escape.php

**Comment by plewin** [comment]
@coudot depends. ldap_escape is not supported under 5.6

People use the polyfill when supporting previous php (like we do in ssp)
https://github.com/symfony/polyfill-php56

Or the original code
https://stackoverflow.com/questions/8560874/php-ldap-add-function-to-escape-ldap-special-characters-in-dn-syntax

**Comment by coudot** [comment]
Hello @plewin 

I think we can require at least php 5.6 for white pages.

**Comment by coudot** [comment]
Done. Just "*" is allowed for the moment in advanced search for default text inputs.

**Comment by nqb** [comment]
Update doc #24 and LTB wiki (https://ltb-project.org/documentation/white-pages/0.2/install_tarball).

Maybe we need to add php 5.6 depends in : 
- `packaging/rpm/SPECS/white-pages.spec` (RPM)
- `packaging/debian/conffiles` (Debian)

**Comment by coudot** [comment]
I'm not sure PHP < 5.6 is still packaged on current Deb/RPM distros. We have PHP 5.6 on CentOS 6 and PHP 7 on CentOS 7.

**Comment by nqb** [comment]
Debian Wheezy (oldoldstable) has PHP 5.4.45 but I don't know if we can run WP on that distro (regarding other depends).

**Comment by coudot** [comment]
It's not a problem to not support such old versions. Wheezy is supported by Debian as LTS only until may 2018: https://www.debian.org/releases/wheezy/
