### ISSUE TITLE
Could be nice to have edition...

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/white-pages#3]
Hi,
I don't know if it is foreseen, but is it planned to allow edition for users and groups?

**Comment by coudot** [comment]
Hi @davidcoutadeur, see also #2 

For the moment I keep to recommend Fusion Directory for edition, but maybe we will introduce some simple edition in future releases. This implies to add authentication/authorization layer, which is not implemented at all for the moment.

**Comment by davidcoutadeur** [comment]
Ok, sorry for the "already-answered question"
