### ISSUE TITLE
Config.inc.php : include local file and document variables

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#30]
Hello,

I would like to suggest two improvements on config file : 
#### adding following code at end of file to include a local config file (that overrides `config.inc.php`) : 
```php
# Include local config file
if (file_exists (dirname (__FILE__) . '/config.inc.local.php')) {
   include dirname (__FILE__) . '/config.inc.local.php';
}
```
There is more than one way to do it. This improvement will be very useful to : 

1. keep an up-to-date `config.inc.php` when doing WP upgrades.
2. customize simply WP installation 

#### syncing documentation between LTB's wiki and config.inc.php

Will be nice to have same documentation between LTB's wiki and config.inc.php. Currently, LTB's wiki documentation is the most complete.

**Comment by coudot** [comment]
> adding following code at end of file to include a local config file

I don't know what are he best practices for that. It seems weird to have 2 config files. Maybe we should have in code all default values, and config file will just be used for modified values?

> syncing documentation between LTB's wiki and config.inc.php

Not really agree too. PHP file is not a documentation file.

We can imagine to create a simple HTML export of the wiki if needed.

**Comment by nqb** [comment]
> I don't know what are he best practices for that. It seems weird to have 2 config files. 

To my mind, it's a best practice. Many softwares use this tip : BIND9, [Dokuwiki](https://www.dokuwiki.org/config#what_can_be_configured) etc. Code given in my first comment comes from [php-memcached-dev](https://github.com/php-memcached-dev/php-memcached/blob/67750f851ad01d054401ce988fe95f7bfe4cb9bf/tests/config.inc#L3).

As maintainer, you have one config file to maintain. Local file is for users.

Currently, with one config file, upgrading WP is really painful : 
1. backup your config file
2. upgrade WP
3. restore your config file
4. make diff between upstream config file and your config file to add new variables
5. use WP

With two config files, you can skip steps 1, 3 et 4.

> Maybe we should have in code all default values, and config file will just be used for modified values?

Not agree, users doesn't need to know PHP language to read config. Besides, you need rewrite code because you use `require_once("../conf/config.inc.php");` in several files. With my solution, no patch needed.

> We can imagine to create a simple HTML export of the wiki if needed.

As you want.

**Comment by nqb** [comment]
@coudot : if I convince you, we also need to add a note on top of `config.inc.php` like this : 
```php
/**
 * All the default values are kept here, you should not modify it but use
 * config.inc.local.php file instead to override the settings from here.
*/
```
Extract from [Dokuwiki's code](https://github.com/splitbrain/dokuwiki/blob/081d7365a19e65810b237098556fc1ff03ff0c57/conf/dokuwiki.php).

**Comment by nqb** [comment]
Upon reflection on syncing documentation between LTB's wiki and config.inc.php, we need to have at least one sentence for variable in `config.inc.php`. There is many variables, having a quick help is really useful.

**Comment by coudot** [comment]
I also this kind of request for Self Service Password: https://github.com/ltb-project/self-service-password/pull/72

Your solution seems nice (using config.inc.local.php). This will require some changes in packaging as config.inc.php is flagged as a config file, and so is not replaced in package updates. We now need to let it as a standard program file, so it will be replaced. Users will only set configuration settings in the local file.

Regarding documentation, we can indeed put a quick help line in config.inc.php.

**Comment by nqb** [comment]
@coudot : what about Debian/RPM packaging ?

**Comment by coudot** [comment]
As discussed, we will not put config.inc.local.php in packages, users can create this file if they want to keep the original config.inc.php, or choose to edit config.inc.php directly and merge changes when packages are updated.
