### ISSUE TITLE
Improve browsing on pages with Datatables

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#34]
See [my comment on #28](https://github.com/ltb-project/white-pages/pull/28#issuecomment-368868100).

Two improvements that can be done with Datatables : 
* Browsing buttons at the top of pages. Currently, only at the end of pages.
* Possibility to go on specific page. Currently, if you have 50 pages and you want to go on page 12, it's really painful.

**Comment by coudot** [comment]
First point is done but second point needs specific code as this is not possible by default in datatables.

I think this is enough for the moment.
