### ISSUE TITLE
Sort icons should be more close than their column name

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#35]
#28 fix wrong display for Firefox/Chrome. 

However, with IE11, you always have wrong display : 
![ie11](https://user-images.githubusercontent.com/10830260/36796446-e2ef505e-1ca5-11e8-88bf-635e0e9f3116.png)

**Comment by nqb** [comment]
@proxyconcept,

Tip of the day : plugin IE Tab v2 can be use with Firefox to have IE's display ;-)

**Comment by coudot** [comment]
I made a change, @nqb could you test?

**Comment by nqb** [comment]
@coudot 

Tested with IE11 and IE Tabv2, display is slighty different from Firefox : sort icons are not completely align with bottom of column names. See below : 
![ie](https://user-images.githubusercontent.com/10830260/36984907-30c1c94e-2096-11e8-86cd-3d57ca348049.png)

**Comment by coudot** [comment]
Ok, but I will not spend too much time on fixing IE CSS bugs. If this is ok for you, I think we can close the issue.
