### ISSUE TITLE
Logo not visible on other pages than homepage

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#37]
Hello,

When you use menus on WP, you don't see logo which is display on homepage (in the middle).

Is it possible to change its location to see it when you browse through WP menus ?

**Comment by coudot** [comment]
Why not, but where?

**Comment by nqb** [comment]
On websites, a common usage is "a clickable logo in the upper left corner of every page on the site" (see [Web Design Standards: 10 Best Practices on the Top 50 Websites](https://www.orbitmedia.com/blog/web-design-standards/)).

In WP, we already have this behavior with `$messages['title']`. Maybe we can locate logo next to.

**Comment by coudot** [comment]
Now logo is in menu, let me know if this looks good to you

**Comment by nqb** [comment]
LGTM.
