### ISSUE TITLE
Text and look for print buttons

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#38]
Hello,

Commit 2f8aca7 changes look and text of print buttons, suggestions : 
* `Complete list` and `Current page` are not clear. Replace by : 
  * `Print all results` and `Print this page` buttons
or
  * `All results` and `This page` buttons with word `Print` (not button) at beginning of the line
* Separate buttons (currently they are dangerously close)

**Comment by coudot** [comment]
Ok to adapt labels, but buttons are managed by datatables, we can't separate them.

**Comment by nqb** [comment]
@coudot : are you sure ? 

Take a look at [Multiple button groups doc](https://datatables.net/extensions/buttons/examples/initialisation/multiple.html). I see separate buttons (Button 2 and Button 3).

**Comment by coudot** [comment]
@nqb we already use this syntax for buttons, but with bootstrap, buttons are grouped.

**Comment by nqb** [comment]
Ok @coudot. LGTM.
