### ISSUE TITLE
Italian language file

### ISSUE THREAD

**Issue by forlanim** [ltb-project/white-pages#4]
I've translated to italian white pages, but i don't known how/where send language file.
Please tell me, thanks.

**Comment by coudot** [comment]
You can join the file here or do a pull request, as you want

**Comment by forlanim** [comment]
the fastest way, here the file (added extension txt to upload)
[it.inc.php.txt](https://github.com/ltb-project/white-pages/files/1314435/it.inc.php.txt)

**Comment by coudot** [comment]
File imported, thanks!
