### ISSUE TITLE
Displaying binary data attributes

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#40]
Hello,

I need to display `objectGUID` attribute in White Pages.

I define a `guid` attribute in my config file : 
`    'guid' => array( 'attribute' => 'objectguid', 'faclass' => 'user', 'type' => 'text' ),`

With this config, I get following display : 
![objectguid](https://user-images.githubusercontent.com/10830260/37698948-8193eb08-2ce5-11e8-8296-31f21ba7e43a.png)

It seems that White Pages try to transform binary data in UTF-8 form.

Could we add a new type of attribute for this data ?

**Comment by coudot** [comment]
Yes a new type is required.

Tip: https://secure.php.net/manual/en/function.ldap-get-values-len.php#117700

**Comment by coudot** [comment]
@nqb to be tested

**Comment by coudot** [comment]
Yes substring matching is not allowed. I will remove the substring possibility for this type and also for all dn_link types.

**Comment by coudot** [comment]
Fixed in latest commit, I think we can close this issue now.

**Comment by nqb** [comment]
I complete doc on that point.
