### ISSUE TITLE
"Display Entry" is empty for the result of a search

### ISSUE THREAD

**Issue by adminrezo** [ltb-project/white-pages#45]
When I search a name, I get a list of corresponding users but when I click on "Display Entry" for a user, his/her card is empty.
Debugging is on but I see no errors and also no errors in the Apache error log.

Php 7.1, Apache 2.4, Debian Stretch, WhitePages 0.2-2 (Debian Package)

Thx a lot for your work !

**Comment by coudot** [comment]
Can you see what is configured in $display_items ? This should list all attributes displayed.

Check also logs on LDAP server side.

**Comment by adminrezo** [comment]
I didn't change it : 
`
$display_items` = array('firstname', 'lastname', 'title', 'businesscategory', 'employeenumber', 'employeetype', 'mail', 'phone', 'mobile', 'fax', 'postaladdress', 'street', 'postalcode', 'l', 'state', 'manager', 'secretary', 'organizationalunit', 'organization', 'description', 'memberof');`

My config is above : 
`$lang = "fr";
$ldap_url = "MY SERVERS";
$ldap_binddn = "MY MANAGER";
$ldap_bindpw = "MY PASS";
$ldap_base = "MY BASE";
$ldap_user_base = "ou=utilisateurs,".$ldap_base;
$ldap_user_filter = "(objectClass=inetOrgPerson)";
$ldap_user_filter = "(objectClass=Person)";
$ldap_group_base = $ldap_user_base;
$ldap_group_filter = "(|(objectClass=group)(objectClass=posixGroup))";

$attributes_map = array(
    ...
    'fullname' => array( 'attribute' => 'displayname', 'faclass' => 'user-circle', 'type' => 'text' ),
    ...
    'office' => array( 'attribute' => 'physicalDeliveryOfficeName', 'faclass' => 'building', 'type' => 'text' ),
    ...
);

$search_result_items = array('mail', 'phone', 'office', 'memberof');

$debug = true;
$use_directory = false;
$use_gallery = false;
$use_vcard = false;
$use_csv = false;`

**Comment by coudot** [comment]
Why do you have twice $ldap_user_filter ?

**Comment by adminrezo** [comment]
Sorry, I forgot it. But it doesn't fix my problem.

**Comment by coudot** [comment]
Put your Apache logs and LDAP logs here so we can have a look

**Comment by coudot** [comment]
I think I see the issue: your group base is the same than your user base. White pages uses it to match againts the entry DN to know which kind of object it is.

Set a different group base.

**Comment by adminrezo** [comment]
Hi @coudot,

Thanks a lot for your help.
The problem is solved.

**Comment by coudot** [comment]
Great!
