### ISSUE TITLE
Add an attribute which doesn't exist in WP

### ISSUE THREAD

**Issue by adminrezo** [ltb-project/white-pages#46]
Hi,

Is it possible to add a LDAP attribute which is not defined in WP by default.
The attributes I need is the office number (physicalDeliveryOfficeName) and maybe the userAccountControl to see if a user is active or disabled.

I tried to declare in my conf file : 
```
$attributes_map = array(
    ...
    'office' => array( 'attribute' => 'physicalDeliveryOfficeName', 'faclass' => 'building', 'type' => 'text' ),
    ...
)
```

In the lang/fr.inc.php, I added this :
```
$messages['label_office'] = "Bureau";
```

When I show a user the office number appears Empty.
Is there anything else to do ?

Thanks in advance.

**Comment by coudot** [comment]
You are not very far from the solution, it is just that PHP LDAP is putting all attributes names in lowercase.

So you can add your attribute with:
```php
  $attributes_map[office] = array( 'attribute' => 'physicaldeliveryofficename', 'faclass' => 'building', 'type' => 'text' );
```

Do this in conf/config.inc.local.php to not erase the defaut configuration. You can also override labels in conf/fr.inc.php.

**Comment by nqb** [comment]
I emphase WP's doc on that point : https://ltb-project.org/documentation/white-pages/0.2/config_attributes?do=diff&rev2%5B0%5D=1523343585&rev2%5B1%5D=1525253845&difftype=inline

**Comment by adminrezo** [comment]
Nice, it works, thanks a lot !
