### ISSUE TITLE
Feature request : add export to CSV

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#5]
Hello,

Could you add a feature to export a search result to CSV (in a row form) ?
My goal is to print an export for end users.

**Comment by coudot** [comment]
Yes, interesting feature!

**Comment by coudot** [comment]
Sample code : https://stackoverflow.com/questions/4249432/export-to-csv-via-php#13474770

**Comment by coudot** [comment]
Documentation created: https://ltb-project.org/documentation/white-pages/0.2/config_csv

**Comment by nqb** [comment]
Hi,

At fd85544 commit, this feature doesn't work.

Steps to reproduce : 
- Go on advanced search page
- Fill "Firstname" row
- Click on "Download results as CSV"
=> Server doesn't return CSV file.

Apache access log : 
```
[21/Dec/2017:12:15:55 +0100] "POST /index.php?page=advancedsearch HTTP/1.1" 500 185 "http://wp.example.com/index.php?page=advancedsearch"
```

Apache error log : 
```
[Thu Dec 21 13:37:34.650501 2017] [:error] [pid 13854] [client X.X.X.X:55908] PHP Warning:  require_once(../lib/csv.inc.php): failed to open stream: No such file or directory in /usr/local/white-pages/htdocs/advancedsearch.php on line 88, referer: http://wp.example.com/index.php?page=advancedsearch
```

In `/usr/local/white-pages/lib`, there is no `csv.inc.php` file ! A forget ?

**Comment by coudot** [comment]
@nqb you are right, the file was missing. It has just been pushed.

**Comment by nqb** [comment]
Thanks @coudot. It works !

Two suggestions for this enhancement : 
* Export results as CSV **after** a search. Currently, export is possible **before** a search. Consequently, you don't know what you are exporting.
* Use advanced search fields (First name, Last Name, Mail, etc.) as CSV columns (headers) in place of LDAP attributes.

Do you want an issue for each suggestion ?

**Comment by coudot** [comment]
>   Export results as CSV after a search. Currently, export is possible before a search. Consequently, you don't know what you are exporting.

Indeed, but this requires to repost the data from the form, so have an hidden form in results page. Not very clean in the code, but I understand the need. You can open a feature request for this, but I am not sure to do it for the moment.

> Use advanced search fields (First name, Last Name, Mail, etc.) as CSV columns (headers) in place of LDAP attributes.

Are you talking about using the labels? Yes I think this could be done easily.

**Comment by nqb** [comment]
> Are you talking about using the labels?

I don't understand what is labels. 

I just think that when you use advanced search with fields like First Name, Last Name, Mail, Title, etc and click on "Download results as CSV", it will be more clear to have CSV file like this : 
```
First Name,Last Name,Mail,Title,
Nicolas,Quiniou-Briand,mail@example.com,,
```
rather than
```
cn,mail,mobile,sn,telephonenumber
nqb,mail@example.com,Quiniou-Briand,6666
```

**Comment by nqb** [comment]
@coudot,

Would you like a dedicated issue(s) for enhancements mentioned in my previous comment ?

> CSV fields match $search_result_items fields.

Agree. I notice that two last columns of CSV export are : `search_result_title` and `search_result_sortby`. Expected behavior ?

**Comment by coudot** [comment]
I reopen the issue so we complete this feature

**Comment by coudot** [comment]
@nqb You can now configure CSV items: https://ltb-project.org/documentation/white-pages/0.2/config_csv

**Comment by nqb** [comment]
Hello @coudot 

Great job ! It works for me. I notice that CSV file contains translated columns.

**Comment by nqb** [comment]
Tip : in my config file, I set `$csv_items` like that : 
```
# sync with advanced search fields
$csv_items = $search_result_items;
```
