### ISSUE TITLE
Hide photo box if there is no picture

### ISSUE THREAD

**Issue by bnesson** [ltb-project/white-pages#54]
Hi,

Is there a way to hide photo box on gallery page if there is no picture ?

Regards,

**Comment by coudot** [comment]
Hello,

you want do hide the full card of an entry if the entry has no photo?

If you don't have any photo in your directory, the best is to disable the gallery page:
```php
$use_gallery = false;

**Comment by bnesson** [comment]
Hi,

Yes we want to hide the card in the gallery page if the entry has no photo (we use  local photo)

**Comment by coudot** [comment]
There is no simple solution to do that, as it would require to first search for the photo before displaying the entry, and we do the other way: we display the entry, then the photo.

If the photo were in the LDAP directory, then you would just have to edit the LDAP filter to dismiss people without pictures. But this method is not possible if you use local photo.

**Comment by bnesson** [comment]
Some entries won't have photo but have to be in directory so If we edit the LDAP filter to dismiss people without pictures we won't see them in gallery AND in directory right?

**Comment by coudot** [comment]
Yes but you can just edit the filter in htdocs/gallery.php to only impact the gallery page.

**Comment by bnesson** [comment]
Ok I think we'll do that way, thanks for your help!

**Comment by coudot** [comment]
Hello,

I created a new parameter for next version to override LDAP filter for the gallery.
