### ISSUE TITLE
Can we get a list of all groups

### ISSUE THREAD

**Issue by ZenHarbinger** [ltb-project/white-pages#55]
I'd like to get a list of groups (as designated by filter) that can then be viewed as normal.  Similar to the directory or gallery, but for groups instead of users.
Is there a way to add this?

**Comment by coudot** [comment]
We could indeed add this feature

Note that you can already have th group list by seraching all groups in advanced search

**Comment by ZenHarbinger** [comment]
I've added it to my code base, give me a few days and I'll send in a pull request.

**Comment by coudot** [comment]
I have looked at your code but I will propose another solution, by adding a type in the directory page, so we can switch between users and groups directly in the page. This avoid to create a new page and prevent some code duplication.

**Comment by coudot** [comment]
Done in #63
