### ISSUE TITLE
How to display  the  "Apprentice"  and "Mentor" attributes   in the "Directory"  tab ?

### ISSUE THREAD

**Issue by chipfy** [ltb-project/white-pages#57]
It's a execllent project.  But I encounter a problem during the use.  The problem is that how to display the "Apprentice" and "Mentor" attributes in the "Directory" tab . I can not find any key word  "Apprentice"  or "Mentor"   in  both the  0.2-1 version  and  the latestest  version  source code(master branch in the github ). I download the source codes and  execute the shell command "# egrep -i 'Apprentice' white-pages-master -R" in the linux for lookuping these key words . But I find nothing.  I do not kow how to implement  the "Apprentice"  and "Mentor" attributes   in the "Directory"  tab .  It's my doubt.

**Comment by chipfy** [comment]
![image](https://user-images.githubusercontent.com/15259714/57213176-930adf00-7018-11e9-8123-e7df31c77cd8.png)

**Comment by chipfy** [comment]
![image](https://user-images.githubusercontent.com/15259714/57213280-e715c380-7018-11e9-8529-22f2dfc5ea4d.png)

**Comment by coudot** [comment]
Hello,

"apprentice" and "mentor" are just labels that were overriden for the "star pages" demo.

See https://ltb-project.org/documentation/white-pages/latest/config_attributes to learn how customize attributes.

For example, to display label "Mentor" on attribute "manager", set this in custom lang file:
```php
$messages["label_manager"] = "Mentor";
```

**Comment by chipfy** [comment]
OK . I see about the "Mentor" .  So which attribute is the "Apprentice" label  is mapping to ?  Is it the "secretary" attribute?

**Comment by coudot** [comment]
yes

**Comment by chipfy** [comment]
In other words,  A's manager is C. B's manager is C . C has two secretary attributes about  A and B. Do you mean  that?
If use this design , so the ldap must maintain  both the manager  atrribute of apprentice  and  secretary attribute of mentor at the same time for Upper and lower level relationship.

**Comment by coudot** [comment]
Indeed, but this should be done by the LDAP management software. White Pages is simply a viewer.

**Comment by chipfy** [comment]
OK. Thank you.
