### ISSUE TITLE
The "Directory" tab of  white page   have paging problem when ldap has a lot of  entries.

### ISSUE THREAD

**Issue by chipfy** [ltb-project/white-pages#59]
My ldap has   2000 entries . When I click the "Directory" tab, I find the web page always rolling down following entries  until the web page displays all 2000 entries,  then the web page will finish paging.  The process exhaused a lot of time because of waiting for display 2000 entries. It's terrirble.I think the process need to be optimized for improving user experience.  Nobody want to  wait.  The all entries fetch can  be finshied in the backgroup of program ,not in the foregroup. 
   I find the  "Gallery" tab does not use paging action. When the entry numer is huage , the web page will always dislplay the left entry.

**Comment by chipfy** [comment]
Is nobody responsible  for the project?

**Comment by coudot** [comment]
Why this question? Because you did not get an answer within 24 hours? It is a free software provided by a community, if you need quicker answer, you can pay support or professional services.

If you read the documentation, you will see that you can use paging on server side: https://ltb-project.org/documentation/white-pages/latest/config_ldap#size_limit

**Comment by nqb** [comment]
@chipfy: for such question, you can also use mailing-list https://lists.ltb-project.org/

**Comment by chipfy** [comment]
I  have tried  the sizelimit  parameter in the config.in.php before that. If I set the sizelimit=10, I can fetch only 10 entry. But I have 2000 entries. The left 1900 entries can not be fetched any more.  It's still a problem.

**Comment by chipfy** [comment]
![image](https://user-images.githubusercontent.com/15259714/57441035-b386a380-727b-11e9-9204-a295e2c7f360.png)

**Comment by chipfy** [comment]
> Why this question? Because you did not get an answer within 24 hours? It is a free software provided by a community, if you need quicker answer, you can pay support or professional services.
> 
> If you read the documentation, you will see that you can use paging on server side: https://ltb-project.org/documentation/white-pages/latest/config_ldap#size_limit


I saw the some issuses still open from 2016 or 2018 year.  They  puzzle me. May the askers  do not close the question  in time.

**Comment by coudot** [comment]
> I have tried the sizelimit parameter in the config.in.php before that. If I set the sizelimit=10, I can fetch only 10 entry. But I have 2000 entries. The left 1900 entries can not be fetched any more. It's still a problem.

The Directory view indeed need to load all entries before pagination, because it is done on client side with js.

You can disable the Directory tab and Thumbnail tab to avoid loading the full directory, and only let search pages, which should be enough to read entries.

**Comment by chipfy** [comment]
It's disappointing.   When the  number of employee entries  reach to tens of thousands , the Directory tab seem to be a disaster in the current condition. 
Maybe I can   not use  the white page project solution.
Thanks.

**Comment by coudot** [comment]
See #1 

White pages is a free software, you can contribute of you want to improve it

**Comment by chipfy** [comment]
> See #1
> 
> White pages is a free software, you can contribute of you want to improve it

How much about the function ?

**Comment by chipfy** [comment]
> See #1
> 
> White pages is a free software, you can contribute of you want to improve it

When I am free,  maybe I will imporve the function .

**Comment by artlog** [comment]
on remark : documentation was moved to readthedocs.io so link to get size-limit is now https://white-pages.readthedocs.io/en/latest/ldap-parameters.html#size-limit
