### ISSUE TITLE
Sort group members

### ISSUE THREAD

**Issue by niltongouveajr** [ltb-project/white-pages#60]
When I do an advanced search by group, I can get the group members. However, I have groups with lots of users and if it was possible to sort the members list, it would be easier to find them.

Congrats for very useful tool! :)

**Comment by coudot** [comment]
It could be an enhancement, but you can also do this on server side by sorting attribute values.

In OpenLDAP:
```
olcSortVals: member
```

**Comment by niltongouveajr** [comment]
Hi Clément, thanks for fast reply. 

About your suggestion to do this on server side... Do you know if it is possible to do this in Active Directory?

**Comment by coudot** [comment]
No I think this is not.

**Comment by niltongouveajr** [comment]
OK. Thank you very much.

**Comment by coudot** [comment]
Done in latest commits. In display page, values are now sorted.

Note that for group members, values are the DN of the users, so the sort is on the DN, even if this is not what is displayed (by defaut the cn is displayed).
