### ISSUE TITLE
Quick search not match

### ISSUE THREAD

**Issue by ASLLR** [ltb-project/white-pages#67]
Hi everyone,

I'm just installing White Pages 0.3 (git version) on my test environnent. I use White Pages 0.2 on my production site.

I can see when i use quick search the result is not display, like this : 
![image](https://user-images.githubusercontent.com/37147055/61302974-fd918580-a7e6-11e9-917f-393e0908a7b7.png)

But when i use advanced search we have the correct display : 
![image](https://user-images.githubusercontent.com/37147055/61303202-6973ee00-a7e7-11e9-9a5b-00b0e93d0a84.png)

Thank for help

**Comment by coudot** [comment]
Can you try to add:
```
$ldap_user_regex = "/,ou=users,/i";
```

**Comment by ASLLR** [comment]
i have a config.inc.loal.php file who overight the config.inc.php
i add this line in this file and i restart apache. But nothing change.

**Comment by coudot** [comment]
Can you show what are your LDAP settings?

I updated doc here: https://ltb-project.org/documentation/white-pages/0.3/config_ldap#user_search_parameters

Do you have some logs too?

**Comment by ASLLR** [comment]
This is my LDAP configuration : 
![image](https://user-images.githubusercontent.com/37147055/61305183-aab9cd00-a7ea-11e9-95ea-ebd1627d1d54.png)

I see which log i can sent you

**Comment by coudot** [comment]
Yes, but in which branch are stored your users?

**Comment by ASLLR** [comment]
the ldap_user_base seem to be at root branch.

**Comment by coudot** [comment]
If user accounts are directly under the LDAP server base, then you must find another cirteria to find the entry type. Can you determine from the entry DN if it is a user?

Finding the entry type is mandatory to display the content of the entry. You can set "type=user" as GET parameter of the display page to see if it works.

**Comment by coudot** [comment]
Sorry, the GET parameter will not work, the display page check only the POST data:
```php
    # Find object type
    if (isset($_POST['type'])) {
        $type = $_POST['type'];
    } else if (isset($ldap_user_regex)) {
        if ( preg_match( $ldap_user_regex, $dn) ) {
            $type = "user";
        } else {
            $type = "group";
        }
    } else {
        if ( preg_match( '/'.$ldap_user_base.'$/i', $dn) ) {
            $type = "user";
        }
        else {
            $type = "group";
        }
    }
```

**Comment by coudot** [comment]
@ASLLR did you manage to find the correct configuration settings?

**Comment by ASLLR** [comment]
i don't understand why this function work in WP 0.2 and not work on 0.3 we use the same config between prod and test environment.

what can i change with the GET parameter ? i don't understand too

**Comment by coudot** [comment]
Indeed, it should work with the configuration of 0.2. Please remove the `$ldap_user_regex` parameter and try again.

Can you tell me what is the DN ot the entry you are displaying, and what is the real value for `$ldap_user_base`?

**Comment by ASLLR** [comment]
If i comment the $ldap_user_regex i have this result :
![image](https://user-images.githubusercontent.com/37147055/61542208-6116ef80-aa41-11e9-9814-92684c385c13.png)

it's better but i think a parameter for picture is disable we don't have the same display than 0.2. i see this display on "trombinoscope" menu too

0.2 :  
![image](https://user-images.githubusercontent.com/37147055/61542355-afc48980-aa41-11e9-89e5-cce34f65f0cb.png)

The DN for the user is : CN=asatest,OU=utilisateurs,OU=ouname,DC=domain,DC=.example

$ldap_user_base = "$ldap_base";
$ldap_base = "dc=domain, dc=.example";

I hope these info can help you.

I censor the domain information and the real OU of user but the tree of DN is correct.

**Comment by coudot** [comment]
Hello @ASLLR 

so the display of user attributes is ok, but not the default picture. I don't see what change in 0.3 could trigger this error. Any log?

**Comment by coudot** [comment]
@ASLLR still no picture?

Can you see if there is a difference between 0.2 and 0.3 in the HTML code?

**Comment by ASLLR** [comment]
Hello @coudot sill not. i see the code and logs now.

**Comment by ASLLR** [comment]
i saw log of my firefox and i see "impossible to load picture" on code inspector. the link auto generate don't reponse. i still see other log.

**Comment by ASLLR** [comment]
i don't know if it's linked but we have the same comportement with groups, no display when we click on a group :

![image](https://user-images.githubusercontent.com/37147055/61633534-97e24500-ac8f-11e9-9fcf-b251c19d30ff.png)

And we don't have $ldap_group_regex for solve like we do for user.

**Comment by coudot** [comment]
There must be something wrong in the user/group ldap configuration.

Do you have some logs on server side?

**Comment by ASLLR** [comment]
on server side for picture i have : [Tue Jul 16 10:30:54.235405 2019] [:error] [pid 14070] [client XX.XX.XX.XX:59590] PHP Notice:  Undefined variable: photo_local_ldap_attribute in /usr/local/white-pages/htdocs/photo.php on line 46, referer: http://wp-test.ch-redon.lan/index.php?page=gallery

i search for groups

**Comment by ASLLR** [comment]
on server side for picture i have : [Tue Jul 16 10:30:54.235405 2019] [:error] [pid 14070] [client XX.XX.XX.XX:59590] PHP Notice: Undefined variable: photo_local_ldap_attribute in /usr/local/white-pages/htdocs/photo.php on line 46, referer: http://server/index.php?page=gallery

i search for groups

**Comment by coudot** [comment]
Ok, this is a notice, seems not related to this issue.

**Comment by coudot** [comment]
In your particular case, user objects are in 2 branches of your directory. To handle that, you can use the `$ldap_user_regex` to match this branches in DN, for example:

```php
$ldap_user_regex = "/,(ou=users|ou=accounts),/i";
```
