### ISSUE TITLE
Display account : empty result

### ISSUE THREAD

**Issue by roumano** [ltb-project/white-pages#75]
On a debian 10 fresh install, i'im trying the white-pages tools  ( 0.3-2 deb version)

with this (simplified for testing this issue) configuration file, it's basicaly working  : 
```
# /usr/share/white-pages/conf/config.inc.local.php
```
```php
<?php
$ldap_url = "ldaps://server1.XXXX ldaps://server2.XXXX";
$ldap_base = "dc=XXXX,dc=fr";
$ldap_binddn = "";
$ldap_bindpw = "";
$ldap_user_base = "ou=people,".$ldap_base;
?>
```

- Directory is working
- Gallery is working
- advancedsearch with multiple items found is working
- adancesearch with only one result is working (got first name, last name , ... )

But the display page (if i click form directory or from gallery) got me a empty result : 

![empty result](https://user-images.githubusercontent.com/6402894/62869963-1e32f980-bd19-11e9-912a-43b49b7ff11c.png)

log of the server say : 
```
[Mon Aug 12 15:53:08.976657 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined variable: logout_link in /usr/share/white-pages/htdocs/index.php on line 77, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.001657 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined index: vcard in /usr/share/white-pages/htdocs/display.php on line 61, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.003279 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined offset: 0 in /usr/share/white-pages/htdocs/display.php on line 82, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.003446 2019] [php7:warn] [pid 13056] [client 172.26.15.30:34988] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/white-pages/htdocs/display.php on line 82, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.003535 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined index: vcard in /usr/share/white-pages/htdocs/display.php on line 92, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.003618 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined variable: display_edit_link in /usr/share/white-pages/htdocs/display.php on line 100, referer: http://white-pages.embl.fr/index.php?page=directory
[Mon Aug 12 15:53:09.003716 2019] [php7:notice] [pid 13056] [client 172.26.15.30:34988] PHP Notice:  Undefined offset: 0 in /usr/share/white-pages/htdocs/display.php on line 107, referer: http://white-pages.embl.fr/index.php?page=directory

```

**Comment by coudot** [comment]
Hello @roumano 

Do you have something configured in `$ldap_user_regex` or `$ldap_group_base` ?

**Comment by roumano** [comment]
Hi,
- `$ldap_user_regex` is not configured
- try with `$ldap_group_base` set and unset : same result

**Comment by coudot** [comment]
@roumano it is maybe because there is a default value in config.inc.php

Try to set in your local config:
```php
unset($ldap_user_regex);
```

Or set this value:
```php
$ldap_user_regex = "/,ou=people,/i";
```

**Comment by roumano** [comment]
Hi,
these workarround make it work's : 
`unset($ldap_user_regex);`
Or 
`$ldap_user_regex = "/,ou=people,/i";`

It's possible to change the code to avoid this issue ? 
  - like creating ldap_user_regex content via ldap_user_base variable
  - or unset ldap_user_regex by default

Or it's need to improve the documentation as for me it's not clear why it's not working : 
https://ltb-project.org/documentation/white-pages/latest/config_ldap
> 
>  When an entry is displayed, to help the software to determine if this is a user, you can configure a regular expression:
> 
> $ldap_user_regex = "/,ou=users,/i";
> 
> If you don't set this value, the software will use the search base: if the entry DN is inside the user search base, then it is a user. But this method can be useless depending of your LDAP directory organization.

**Comment by coudot** [comment]
You are right, this value should be unset by default, we will fix this.

The documentation is right, if the regexp is undef, then the software uses the LDAP search base to match the user.

**Comment by coudot** [comment]
Option is now commented. If this is ok for you, we can close the issue.

**Comment by coudot** [comment]
See also https://ltb-project.org/documentation/white-pages/0.3/upgrade
