### ISSUE TITLE
add a option to change timeout of ldap connexion

### ISSUE THREAD

**Issue by roumano** [ltb-project/white-pages#76]
In our Infrastructure, we have a meta ldap (from 4 backend different LDAP) with around 2000 entry

sometime, we got a this error (very shortly like in less than 5 seconds  : 
```
  LDAP communication error 
```

It's will be great, of course to have the #1 issue fixed, but until it, it's possible to change the timeout connection to the LDAP (i get this error in less than 5 seconds) ?

**Comment by coudot** [comment]
Are you sure that the timelimit is not on server side? There is no timeout configured in White Pages.

**Comment by coudot** [comment]
@roumano should be possible with the above pull request.

You can do a simple test by adding this line in lib/ldap.inc.php in function wp_ldap_connect:
```php
ldap_set_option($ldap, LDAP_OPT_NETWORK_TIMEOUT, 10);
```
