### ISSUE TITLE
Doc : fix typo in "Installation from tarball"

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#8]
Hello,

On https://ltb-project.org/documentation/white-pages/latest/install_tarball page, we can read : 

`
You should have installed these programs before running Self Service Password:
`

We should read : 

`
You should have installed these programs before running White Pages :
`

Self Service Password need to be replace by White Pages.

**Comment by coudot** [comment]
Thanks for the report, it is now fixed.
