### ISSUE TITLE
how to use without php-gd

### ISSUE THREAD

**Issue by ken-colvin** [ltb-project/white-pages#90]
Hi,

I am interested in using your software but I do not want to install php-gd.  Please explain how I can use this software without php-gd.

**Comment by coudot** [comment]
php-gd is required to display photos. There is no option to bypass it. Why don't install it?

**Comment by ken-colvin** [comment]
I do not need to display photos and I do not want to install php-gd. 
Please send me instructions on how to bypass displaying photos and where I do not need php-gd.
Thanks

**Comment by coudot** [comment]
This is not possible, you need to patch the code to remove call to photo.php script

**Comment by ken-colvin** [comment]
That is what I want to do.  Please give me a summary where I "patch" so I do not have to use php-gd and I will change the code.

**Comment by coudot** [comment]
Really easy, just remove calls to photo.php in templates:
```
clement@ader-worteks:~/dev/white-pages$ grep -r photo.php
templates/gallery.tpl:                    <img src="photo.php?dn={$entry.dn|escape:'url'}" alt="{$entry.{$attributes_map.{$card_title}.attribute}.0}" class="img-responsive img-thumbnail center-block" />
templates/listing_boxes.tpl:                {if {$type}==="user"}<img src="photo.php?dn={$entry.dn|escape:'url'}" alt="{$entry.{$attributes_map.{$card_title}.attribute}.0}" class="img-responsive img-thumbnail center-block" />{/if}
templates/display.tpl:                <img src="photo.php?dn={$entry.dn|escape:'url'}" alt="{$entry.{$attributes_map.{$card_title}.attribute}.0}" class="img-responsive img-thumbnail center-block" />
