### ISSUE TITLE
slow performance on ldap with ssl

### ISSUE THREAD

**Issue by roumano** [ltb-project/white-pages#99]
With our white pages, it's slow to open the page `index.php?page=directory` (only 86 entries)
After some debugging it's mainly related to ssl on ldap with lot of connexion : 

Tested with curl via this configuration file : `curl.format` 
```
time_total:  %{time_total}\n
```
* **Without ssl** ( configuration ldap_url = "ldap://..." ) 
curl -w "@curl.format" -o /dev/null -s https://XXXX/index.php?page=directory   
  * time_total:  **0.245670**
* **With starttls** ( configuration ldap_url = "ldap://...  + $ldap_starttls = true;" ) 
curl -w "@curl.format" -o /dev/null -s https://XXXX/index.php?page=directory   
  * time_total:  **2.156036**
* **With ldaps** ( configuration ldap_url = "ldaps://..." )
curl -w "@curl.format" -o /dev/null -s https://XXXX/index.php?page=directory   
  * time_total:  **2.083686**

Looking on the slapd log, it's bind/unbind for each query ( so for this page, 87times... ) it's possible to unbind only once per page  ? and eventually use a cache ?

**Comment by coudot** [comment]
No really, because we do an LDAP request to get each photo.

To change this, the LDAP connecion should be cached on server side to be reused by all pages. Not sure this is easy to do.

**Comment by roumano** [comment]
on directory, we use it as a table without picture (we see picture only on the page page=gallery)

Actually, it's look like working as this : 
```
bind 
ldap to get all user
unbind
loop of each user
  bind 
  ldap on a user
  unbind
```

It's possible to avoid bind/unbind all the time, like this ? 
```
bind 
ldap to get all user
unbind
bind 
loop of each user
  ldap on a user
end lopp
unbind
```

**Comment by coudot** [comment]
Which fields are you displaying in the directory table?

**Comment by roumano** [comment]
Hi,
We use 7 fileds : 
* Prénom 
* Nom 
* Titre
* Courriel
* Location
* Téléphone
* Manager

**Comment by coudot** [comment]
The Manager is the problem: this is a DN value, and we need an LDAP request to display the name of this DN. You should remove this attribute from the table.
